var id=0;
export var productsData=[
{
    p_id:++id,
    p_img:'https://happycredit.in/cloudinary_opt/blog/mobile-under-10000-x43aa.webp',
    p_name:"Mobiles"
},
{
    p_id:++id,
    p_img:'https://imgeng.jagran.com/images/2023/oct/Best%2013%20Generation%20Laptops%20In%20India1698484193529.jpg',
    p_name:"Laptops"
},
{
    p_id:++id,
    p_img:'https://www.android.com/static/2016/img/tv/hero/new-tv-hero-mobile@us.webp',
    p_name:"TV"
},
{
    p_id:++id,
    p_img:'https://media.gq.com/photos/5e8c9a7cc21b8b00087a00f1/master/pass/watches-fix.jpg',
    p_name:"Watches"
},
{
    p_id:++id,
    p_img:'https://i.rtings.com/assets/pages/8U3BTJO2/best-wireless-bluetooth-headphones-20230906-medium.jpg?format=auto',
    p_name:"Bluetooths"
},
{
    p_id:++id,
    p_img:'https://3.imimg.com/data3/XD/ST/MY-8359975/new-mobile-power-bank.jpg',
    p_name:"PowerBanks"
},
{
    p_id:++id,
    p_img:'https://img.staticmb.com/mbcontent/images/crop/uploads/2022/12/types-of-fridges_0_1200.jpg',
    p_name:'Fridges'
},
{
    p_id:++id,
    p_img:'https://aws-obg-image-lb-5.tcl.com/content/dam/brandsite/region/in/blog/pc/detail/blog-march/washing-machine-dimensions/banner.jpg',
    p_name:'WashingMachines'
},
{
    p_id:++id,
    p_img:'https://4.imimg.com/data4/RJ/VR/ANDROID-12021088/product.jpeg',
    p_name:'ElectricFans'
},
]